# Change these first
owner: nomodoio # Your GitHub organization or username, where this repository lives
repo: bug-free-train  # The name of this repository

sites:
  - name: Web
    url: https://nomodo.io
    assignees:
      - ecelustka
  - name: Admin BE DEV
    url: https://adminbe-prod.nomodo.io/health
    assignees:
      - podanypepa
  - name: Admin BE PROD
    url: https://adminbe-prod.nomodo.io/health
    assignees:
      - podanypepa
  - name: Wizard BE DEV
    url: https://wizardbe-dev.nomodo.io/health
    assignees:
      - podanypepa
  - name: Wizard BE PROD
    url: https://wizardbe-prod.nomodo.io/health
    assignees:
      - podanypepa
  - name: Web BE DEV
    url: https://webbe-dev.nomodo.io/health
    assignees:
      - podanypepa
  - name: Web BE PROD
    url: https://webbe-prod.nomodo.io/health
    assignees:
      - podanypepa

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname:  status.nomodo.io
  # baseUrl: /your-repo-name
  logoUrl: https://res.cloudinary.com/nomodo/image/upload/w_48,h_48/v1672840628/nomodo-io-slack.svg
  name: Nomodo Status Page
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  # graphs: "0 0 * * *"
  # responseTime: "0 6 * * *"
  # staticSite: "0 1 * * *"
  # summary: "0 0 * * *"
  # updateTemplate: "0 0 * * *"
  # updates: "0 3 * * *"
  uptime: "0 0 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
